# Generated by Django 4.1.7 on 2023-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=32)),
                (
                    "portrait",
                    models.FileField(
                        default="", upload_to="static/users", verbose_name="选择用户头像"
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("nickname", models.CharField(max_length=32)),
                ("gender", models.IntegerField(default=0)),
                ("password", models.CharField(max_length=32)),
                ("song_num", models.IntegerField(default=0)),
                ("mv_num", models.IntegerField(default=0)),
            ],
            options={"db_table": "user",},
        ),
    ]
