# Generated by Django 4.1.7 on 2023-04-22 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Captcha",
            fields=[
                (
                    "email",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("loginCaptcha", models.IntegerField(default=0)),
                ("loginTime", models.IntegerField(default=0)),
                ("registerCaptcha", models.IntegerField(default=0)),
                ("registerTime", models.IntegerField(default=0)),
                ("resetCaptcha", models.IntegerField(default=0)),
                ("resetTime", models.IntegerField(default=0)),
            ],
            options={"db_table": "captcha",},
        ),
        migrations.CreateModel(
            name="SingerTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "singerTag",},
            managers=[("object", django.db.models.manager.Manager()),],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=32)),
                ("portrait", models.CharField(default="", max_length=64)),
                ("score", models.IntegerField(default=0)),
                ("nickname", models.CharField(max_length=32)),
                ("gender", models.IntegerField(default=0)),
                ("password", models.CharField(max_length=64)),
                ("song_num", models.IntegerField(default=0)),
                ("mv_num", models.IntegerField(default=0)),
            ],
            options={"db_table": "user",},
        ),
        migrations.CreateModel(
            name="Singer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(default="", max_length=64)),
                ("name", models.CharField(default="", max_length=64)),
                ("desc", models.CharField(max_length=128)),
                ("tags", models.ManyToManyField(to="myMusic.singertag")),
            ],
            options={"db_table": "singer",},
            managers=[("object", django.db.models.manager.Manager()),],
        ),
        migrations.CreateModel(
            name="MV",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(default="", max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("play_count", models.IntegerField(default=0)),
                ("star_count", models.IntegerField(default=0)),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myMusic.singer"
                    ),
                ),
            ],
            options={"db_table": "mv",},
        ),
    ]
