# Generated by Django 4.1.7 on 2023-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Captcha",
            fields=[
                (
                    "email",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("loginCaptcha", models.IntegerField(default=0)),
                ("loginTime", models.IntegerField(default=0)),
                ("registerCaptcha", models.IntegerField(default=0)),
                ("registerTime", models.IntegerField(default=0)),
            ],
            options={"db_table": "captcha",},
        ),
    ]
