# Generated by Django 4.1.7 on 2023-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0002_remove_mv_singer_mv_desc_mv_publish_singer_mvs"),
    ]

    operations = [
        migrations.CreateModel(
            name="MVTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="mv",
            name="tags",
            field=models.ManyToManyField(to="myMusic.mvtag"),
        ),
    ]
