# Generated by Django 4.1.7 on 2023-04-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0002_captcha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=64),
        ),
    ]
