# Generated by Django 4.1.7 on 2023-04-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="captcha",
            name="resetCaptcha",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="captcha",
            name="resetTime",
            field=models.IntegerField(default=0),
        ),
    ]
