# Generated by Django 4.1.7 on 2023-04-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0003_mvtag_mv_tags"),
    ]

    operations = [
        migrations.AlterModelTable(name="mvtag", table="mvTag",),
    ]
