# Generated by Django 4.1.7 on 2023-04-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0004_alter_mvtag_table"),
    ]

    operations = [
        migrations.AlterModelManagers(name="singer", managers=[],),
    ]
