# Generated by Django 4.1.7 on 2023-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0005_alter_singer_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(default="", max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("publish", models.DateTimeField()),
                ("play_count", models.IntegerField(default=0)),
                ("star_count", models.IntegerField(default=0)),
            ],
        ),
    ]
