# Generated by Django 4.1.7 on 2023-04-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0006_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="singer",
            name="songs",
            field=models.ManyToManyField(to="myMusic.song"),
        ),
        migrations.AddField(
            model_name="song",
            name="mv_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myMusic.mv",
            ),
        ),
        migrations.AlterModelTable(name="song", table="song",),
    ]
