# Generated by Django 4.1.7 on 2023-04-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0007_singer_songs_song_mv_id_alter_song_table"),
    ]

    operations = [
        migrations.RenameField(model_name="song", old_name="mv_id", new_name="mv",),
    ]
