# Generated by Django 4.1.7 on 2023-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0010_album_singer_albums"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="score", new_name="album_num",
        ),
        migrations.AddField(
            model_name="user",
            name="albums",
            field=models.ManyToManyField(to="myMusic.album"),
        ),
        migrations.AddField(
            model_name="user",
            name="mvs",
            field=models.ManyToManyField(to="myMusic.mv"),
        ),
        migrations.AddField(
            model_name="user",
            name="songs",
            field=models.ManyToManyField(to="myMusic.song"),
        ),
        migrations.CreateModel(
            name="UserPlay",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=64)),
                ("publish", models.DateTimeField()),
                ("songs", models.ManyToManyField(to="myMusic.song")),
            ],
            options={"db_table": "userPlay",},
        ),
        migrations.AddField(
            model_name="user",
            name="plays",
            field=models.ManyToManyField(to="myMusic.userplay"),
        ),
    ]
