# Generated by Django 4.1.7 on 2023-05-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myMusic", "0011_rename_score_user_album_num_user_albums_user_mvs_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="mv", name="star_count",),
        migrations.RemoveField(model_name="song", name="star_count",),
    ]
